name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3 # Was "v2" before for Heroku
      - uses: actions/setup-node@v3 # Was "v2" before for Heroku
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') }}
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
      - name: deploy app to Render # Was "Debloy app to Heroku" before for Heroku
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') }}
        uses: johnbeynon/render-deploy-action@v0.0.8 #uses: akhileshns/heroku-deploy@v3.7.8
        with:
          api-key: ${{ secrets.RENDER_API_KEY }}
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          #heroku_app_name: 'fs-open-pokedex' 
          #heroku_email: 'esa.makipaa@gmail.com'
          #healthcheck: 'https://full-stack-open-pokedex-h79l.onrender.com/health'
          #checkstring: 'ok'
          #rollbackonhealthcheckfailed: true
      #- name:  slack success notification
      #  uses: 8398a7/action-slack@v3
      #  with:
      #    status: custom
      #    fields: commit,author,took
      #    custom_payload: |
      #      {
      #        attachments: [{
      #          color: 'good',
      #          text: `A new version deployed to https://fs-open-pokedex.herokuapp.com/ (${process.env.AS_COMMIT}) by ${process.env.AS_AUTHOR}, status: ${{ job.status }}, build took ${process.env.AS_TOOK}.`,
      #        }]
      #      }
      #  env:
      #    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #  if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') && success() }}
      #- name:  slack failure notification
      #  uses: 8398a7/action-slack@v3
      #  with:
      #    status: ${{ job.status }}
      #    fields: repo,commit,eventName,message,author,took
      #    custom_payload: |
      #      {
      #        attachments: [{
      #          color: 'danger',
      #          text: 'Build failure',
      #        }]
      #      }
      #  env:
      #    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #  if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), '#skip') && failure() }}